---
  environment: production 
  #chdir: 
  address: 127.0.0.1
  user: onboard
  group: onboard
  port: 4567
  pid: thin.pid
  rackup: config.ru
  log: thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true
